#!/bin/bash
    
#$ -cwd -l gpus=1

# help with installing torch: https://pytorch.org/get-started/locally/
    
# instead of source use . to activate they python virtual environment with torch installed
. ~/Library/compute_grid_venv/bin/activate

    
# python3 -c "import torch; print('hello', torch.cuda.is_available())"

for ckpt in $(seq 100 100 3200);
do
    echo checkpoint-$ckpt;
    for i in $(seq 1 3);
    do
    python3 run_generation.py --model_type=gpt2 --model_name_or_path=ckpt_nytimes_c/checkpoint-$ckpt --length=527 \
            --prompt "<|beginauthors|> nytimes <|endofauthors|>" --stop_token "<|endoftext|>" --seed $i;
    done
    echo '';
done

deactivate
